/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as MapRouteImport } from './routes/map'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as EquityRouteImport } from './routes/equity'
import { Route as DemandRouteImport } from './routes/demand'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutesIndexRouteImport } from './routes/routes.index'
import { Route as RoutesIdRouteImport } from './routes/routes.$id'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const EquityRoute = EquityRouteImport.update({
  id: '/equity',
  path: '/equity',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandRoute = DemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIdRoute = RoutesIdRouteImport.update({
  id: '/routes/$id',
  path: '/routes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/budget': typeof BudgetRoute
  '/demand': typeof DemandRoute
  '/equity': typeof EquityRoute
  '/fleet': typeof FleetRoute
  '/incidents': typeof IncidentsRoute
  '/map': typeof MapRoute
  '/predictions': typeof PredictionsRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/weather': typeof WeatherRoute
  '/routes/$id': typeof RoutesIdRoute
  '/routes/': typeof RoutesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/budget': typeof BudgetRoute
  '/demand': typeof DemandRoute
  '/equity': typeof EquityRoute
  '/fleet': typeof FleetRoute
  '/incidents': typeof IncidentsRoute
  '/map': typeof MapRoute
  '/predictions': typeof PredictionsRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/weather': typeof WeatherRoute
  '/routes/$id': typeof RoutesIdRoute
  '/routes': typeof RoutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/budget': typeof BudgetRoute
  '/demand': typeof DemandRoute
  '/equity': typeof EquityRoute
  '/fleet': typeof FleetRoute
  '/incidents': typeof IncidentsRoute
  '/map': typeof MapRoute
  '/predictions': typeof PredictionsRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/weather': typeof WeatherRoute
  '/routes/$id': typeof RoutesIdRoute
  '/routes/': typeof RoutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/budget'
    | '/demand'
    | '/equity'
    | '/fleet'
    | '/incidents'
    | '/map'
    | '/predictions'
    | '/safety'
    | '/settings'
    | '/simulator'
    | '/weather'
    | '/routes/$id'
    | '/routes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/budget'
    | '/demand'
    | '/equity'
    | '/fleet'
    | '/incidents'
    | '/map'
    | '/predictions'
    | '/safety'
    | '/settings'
    | '/simulator'
    | '/weather'
    | '/routes/$id'
    | '/routes'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/budget'
    | '/demand'
    | '/equity'
    | '/fleet'
    | '/incidents'
    | '/map'
    | '/predictions'
    | '/safety'
    | '/settings'
    | '/simulator'
    | '/weather'
    | '/routes/$id'
    | '/routes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BudgetRoute: typeof BudgetRoute
  DemandRoute: typeof DemandRoute
  EquityRoute: typeof EquityRoute
  FleetRoute: typeof FleetRoute
  IncidentsRoute: typeof IncidentsRoute
  MapRoute: typeof MapRoute
  PredictionsRoute: typeof PredictionsRoute
  SafetyRoute: typeof SafetyRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  WeatherRoute: typeof WeatherRoute
  RoutesIdRoute: typeof RoutesIdRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equity': {
      id: '/equity'
      path: '/equity'
      fullPath: '/equity'
      preLoaderRoute: typeof EquityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand': {
      id: '/demand'
      path: '/demand'
      fullPath: '/demand'
      preLoaderRoute: typeof DemandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$id': {
      id: '/routes/$id'
      path: '/routes/$id'
      fullPath: '/routes/$id'
      preLoaderRoute: typeof RoutesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BudgetRoute: BudgetRoute,
  DemandRoute: DemandRoute,
  EquityRoute: EquityRoute,
  FleetRoute: FleetRoute,
  IncidentsRoute: IncidentsRoute,
  MapRoute: MapRoute,
  PredictionsRoute: PredictionsRoute,
  SafetyRoute: SafetyRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  WeatherRoute: WeatherRoute,
  RoutesIdRoute: RoutesIdRoute,
  RoutesIndexRoute: RoutesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
